### ISSUE TITLE
一个由TG官方功能引起的问题

### ISSUE THREAD

**Issue by Hitiko** [Elepover/pmcenter#13]
刚刚我帮一个人搭建pmcenter，他搭完之后让我回复他的bot测试，他一直回复不了
排查到最后发现是Telegram Forwarded Messages功能的问题，如果用户禁止转发消息的话，bot主人无法回复用户
不知是否有解决方案，除了让用户关闭forward protect

**Comment by Elepover** [comment]
pmcenter 在版本 1.5.87.176 (commit [#65da89d7](https://github.com/Elepover/pmcenter/commit/65da89d7d16e3a657d0faf74622a1e409462fca7)) 中已加入匿名转发修正，请尝试启用 `EnableMsgLink` 功能，具体可参见[文档](https://github.com/Elepover/pmcenter/blob/master/README_zh.md#pmcenter-设置)及相关[注意事项](https://github.com/Elepover/pmcenter/blob/master/README_zh.md#注意事项)
