### ISSUE TITLE
最新版不能进行info指令

### ISSUE THREAD

**Issue by cccyyk** [Elepover/pmcenter#31]
如题[图片](https://ae01.alicdn.com/kf/Uc851d527d912422ea3d52a8cf7041f677.jpg)

**Comment by Elepover** [comment]
请参见[常见问题/为什么我无法回复匿名转发的消息？](https://github.com/Elepover/pmcenter/blob/master/README_zh.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%97%A0%E6%B3%95%E5%9B%9E%E5%A4%8D%E5%8C%BF%E5%90%8D%E8%BD%AC%E5%8F%91%E7%9A%84%E6%B6%88%E6%81%AF)

此为 Telegram 5.5.0 引入的新功能（见 issue #13），pmcenter 已在版本 `1.5.87.176` 中修复。

如问题仍未解决，欢迎随时补充信息（如日志）reopen issue.
