### ISSUE TITLE
一个问题，一个建议。

### ISSUE THREAD

**Issue by 1424753988** [Elepover/pmcenter#9]
问题：管理员通过机器人回复用户的消息时，机器人会通过转发的形式将管理员的账号昵称信息一同转发过去，这样会导致管理员的账号隐私泄露，换句话说，这样的机器人意义就不大了。
建议：增加消息撤回、编辑功能。

**Comment by 1424753988** [comment]
![Screenshot_2019-03-10-12-23-58-892_org telegram m](https://user-images.githubusercontent.com/40623378/54080644-942cd200-432f-11e9-94a3-37c63e78f086.png)
可以参考这个机器人的消息发送方式。

**Comment by Elepover** [comment]
这个功能是有的，在设置里启用 `AnonymousForward` 即可。

至于消息撤回及编辑，应该会在后期版本加入_(:з」∠)_

**Comment by Elepover** [comment]
看上去 TG 新版有原生支持匿名转发了..

https://t.me/KugelblitzEH/3633

**Comment by Elepover** [comment]
消息撤回和编辑，实现的话感觉会需要一个新的 database，我可能会做成一个可选功能

**Comment by Elepover** [comment]
TG 5.5.0 加上这个功能了

然后又得开一个新的 issue 来解决一些新问题
